### ISSUE TITLE
"Unsure" values are not saved

### ISSUE THREAD

**Issue by p3zo** [MTG/mtg-arousal-valence-annotator#7] opened 2022-03-15 20:56 UTC
I used the "I am not sure" checkbox during annotation, but found that the `unsure_arousal` and `unsure_valence` values in my final annotations were always `off`.

**Comment by dbogdanov** [comment] 2022-03-15 20:58
Hmm, when we annotated ourselves we did not get into this error. @palonso?

**Comment by p3zo** [comment] 2022-03-15 21:13
Removing the `value="off"` attributes from the [input tags](https://github.com/MTG/mtg-arousal-valence-annotator/blob/main/templates/arousal_and_valence.html#L21) fixes it for me.

Maybe you did your annotations before those were added in https://github.com/MTG/mtg-arousal-valence-annotator/commit/c227ec5e76733d0dcfce47043a39abef78a7f5c9?

**Comment by sonoalex** [comment] 2022-03-15 23:16
After reading this, I have checked my annotation files, in which I remember being added some "unsure", and realised that all of them are "off"...

**Comment by dbogdanov** [comment] 2022-03-16 10:47
This has been fixed in #8.

In your assignment, in the case you used previous version of annotator, exclude analysis related to "unsure".

In our pre-evaluation with three annotators before the bug was introduced, we found that "unsure" checkboxes were seldomly used, only for 5% of the annotated pairs. We cannot generalize to other annotators though.

**Comment by palonso** [comment] 2022-03-16 10:47
I've reproduced the issue and I confirm the bug.
However, I think it was introduced in https://github.com/MTG/mtg-arousal-valence-annotator/commit/060c2686a6c0e72936bbfe294caf5f69fcfc1e30#
The problem is that I [moved the checkbox outside the box class](https://github.com/MTG/mtg-arousal-valence-annotator/blob/060c2686a6c0e72936bbfe294caf5f69fcfc1e30/templates/arousal_and_valence.html#L23I), so the form always picks the default value.

@dbogdanov if I recall well, this change was made with the feedback we got from our first annotation days, so in my case the bug should be present on the last pages of annotations only.

I tried @p3zo's  solution, but it didn't work for me, so I fixed it in #8 by putting the checkbox back into the `box` class.

Thanks for reporting @p3zo and @sonoalex  and apologies for my poor web skills! :sweat:

**Closed** 2022-03-16 10:47 UTC
